# if variable not defined in the env that
# run the make command from , it should be
# exported in the Makefile to be exported the
# environment of all the sub-commands below it
# in the makefile (defined globally in the Makefile)

export FOO=bar
all:
	@echo FOO is $$FOO
