# run with -e option for make : make -e

PATH="Nothing"
override LOGNAME="Mahdi"

orig=$(info $(LOGNAME) $(origin LOGNAME))
orig2=$(info $(PATH) $(origin PATH))

show:
	echo $(orig)
	echo $(orig2)
	echo "As you see PATH is not changed using make -e "
